# Base configs
baseurl: "https://amitlzkpa.github.io/temperhari"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Sketches by Narahari"
subtitle: "Sketch sketch sketch!"
author: "Narahari"
header:
 title: "Sketches"
 subtitle: "by Narahari"
footer:
 name: "Hey there, my name is Narahari"
 bio: "I am not a fish."
 github: ""
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: ""
  instagram: "https://www.instagram.com/narahari.b30/"
  dribbble: ""
  linkedin: ""
  github: ""
